apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework_2_helm.fullname" . }}
  labels:
    {{- include "homework_2_helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "homework_2_helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homework_2_helm.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /otusapp/artem/health
              port: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: homework-config
                  key: NODE_ENV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: homework-secret
                  key: DATABASE_URI
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: homework-secret
                  key: DB_USER
            - name: DB_PSWD
              valueFrom:
                secretKeyRef:
                  name: homework-secret
                  key: DB_PSWD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: homework-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: homework-config
                  key: DB_PORT
